version: "3"

services:
  
  zookeeper:
    image: 'zookeeper:3.7'
    container_name: zookeeper
    ports:
      - '2181:2181'
  
  kafka-server:
    image: 'bitnami/kafka:3.1.0'
    container_name: kafka-server
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-clock-producer:
    build: ./kafka/
    image: kafka:latest
    container_name: kafka-clock-producer
    depends_on:
      - kafka-server